server:
  port: 3000
  host: localhost
db:
  host: localhost
  database: MyDatabase
jwt:
  secret: H9XVhpaHhNuoHkGNQ4vk
  options:
    expiresInMinutes: 60*24*7
    subject: authenticate
assets:
  root: ../statistikwbt-client/dist
  index: index.html
